### ISSUE TITLE
self.emitter has been renamed as self.bus

### ISSUE THREAD

**Issue by witlingw** [CarstenAgerskov/skill-mosquito-speak#3]
When trying to use the _utterance option an error occurs saying that "MosquitoSpeak has no attribute emitter".

Apparently emitter has been renamed as bus (I tested it locally and it worked). See also following threads:
https://community.mycroft.ai/t/cmd-skill-not-work-anymore-since-28-feb-update/5991/3
https://github.com/forslund/cmd_skill/commit/0d8a64946a69a42a17f6c548fd665c199f619b4a

**Comment by CarstenAgerskov** [comment]
Thanks for finding and reporting this.

Regards Carsten

**Comment by elmicha** [comment]
Somehow the [current version](https://github.com/CarstenAgerskov/skill-mosquito-speak/blob/46a422b3020c7eb64ef5023222c4d80d4b03d468/__init__.py#L80) has `self.emitter.emit` again. I changed it to `self.bus.emit` and it works.

Best regards...
  Michael

**Comment by pinki84** [comment]
Thanks it works I added 
self.enclosure.deactivate_mouth_events()
self.enclosure.mouth_text(m)
after 
self.speak(m) on line 98
to display message on Mark 1 display

**Comment by CarstenAgerskov** [comment]
Thanks everyone, for spotting those things.
I will look into it.

**Comment by CarstenAgerskov** [comment]
@pinki84 
I don't have a Mark 1. Reading the docs, it seems that self.enclosure.mouth_text(m) should suffice.
Looking through the mycroft-core code, I can't find any self.enclosure.activate_mouth_events(). 
If self.enclosure.deactivate_mouth_events() is not called, for how long does the Mark 1 display the text? 
Are mouth events reactivated automatically if self.enclosure.deactivate_mouth_events() is called, and when? 
I would rather avoid using self.enclosure.deactivate_mouth_events(), without some Mycroft doc to support it, to prevent something from breaking in the future.

Thanks

**Comment by pinki84** [comment]
I found it on 
def show_date_mark1(self, location, day):
        show = self.get_display_date(day, location)
        self.enclosure.deactivate_mouth_events()
        self.enclosure.mouth_text(show)
line 541 of date time skill
and if u need to display icons/images :


```
def on_message(self, client, userdata, msg):
        try:
            m = msg.payload.decode('utf-8')
            if m.startswith('icon='):
                self.enclosure.mouth_display(img_code="HIAAAAAAAAAAAAAA", refresh=False)
                self.enclosure.mouth_display(img_code="HIAAAAAAAAAAAAAA", x=16, refresh=False)
                temp = "\"" +  m.split('=', 1)[1]+ "\""
                self.enclosure.mouth_display(m.split('=', 1)[1] ,x=1,refresh=False)
                LOG.error(temp)
                time.sleep(5)
                self.enclosure.reset()
                return
            if m.startswith('_utterance') and len(m.split(' ', 1)) > 1:
                self.bus.emit(
                    Message('recognizer_loop:utterance',
                            {'lang': 'en-us',
                             'utterances': [m.split(' ', 1)[1]]}))
                return
            if self.splitRegex:
                m = re.sub(self.splitRegex, lambda x:
                    x.group(0)[0:int(self.retainFirst)] +
                    ' ' + x.group(0)[int(self.retainLast):], m)

            if self.sleep_mode and msg.topic != self.alertTopic:
                LOG.info('Sleep Mode. Skipping voice output for message: ' + m)
            else:
                self.speak(m)
                self.enclosure.deactivate_mouth_events()
                self.enclosure.mouth_text(m)
                    
            self.last_message = m

        except Exception as e:
            LOG.error('Error: {0}'.format(e))

```
Mqtt message :
`icon=QIAAAAOHGEKEKECFCFCFCFKEKEGEOHAAAA`
will display envelope I will add x and y 
this way thanks to your skill I can send information to display from home assistent over mqtt

**Comment by CarstenAgerskov** [comment]
I renamed the emitter to bus, thanks to @witlingw and @elmicha

I added Mark 1 enclosure support "in the blind", since I have no Mark 1 to test it on :) Thanks to @pinki84 for the research.
