### ISSUE TITLE
mqtt server ip gets lost

### ISSUE THREAD

**Issue by JoergZ2** [CarstenAgerskov/skill-mosquito-speak#6]
I'm a newbie in using Mycroft resp. Picroft. This are my first steps. I've been working with SNIPS, which is currently running. But the public support has ended on January 31. So I'm looking for alternatives. I've some experiences on working with mqtt and wrote a python-script, which is analyzing the hermes/intent topic and gives output to hermes/tts.

There is a problem using your script: The mqtt server's ip is always "forgotten" after rebooting. And I'm not sure where the mqtt ip has to be stored. First I edited __init__py and changed the class MosquitoSpeak(MycroftSkill) with this parameters:
```
        self.host = '192.168.178.20'
        self.port = '1883'
        self.topic = 'my-out/text'
        self.alertTopic = 'my-alert'

```
I got a Error: no host an nothing worked (e. g. sending a text to my-out/text, nothing was spoken)
Then I edited settings.json:
"host": "192.168.178.20", "port": 1883, "topic": "my-out/text", "alertTopic": "my-alert" 
After a reboot of Picroft a messsage sended to my-out/text -m "Hallo World" is spoken by Mycroft. But after the next reboot it does not work again and the values for host, topic and alertTopic in settings.json are empty again. What is my failure?

**Comment by CarstenAgerskov** [comment]
Hi Joerg
Did you set the configuration on your Mycroft home? (https://account.mycroft.ai/skills)
I suspect local changes to the settings.json file might be overwritten.
Regards Carsten

**Comment by JoergZ2** [comment]
That was the decisive clue! Many thanks! I had installed Mosquito-speak manually and didn't see that there was a change in skills. I'm beginning to understand how Mycroft work. I am just a beginner.  There is obviously a lot of cloud connection. It's not really my thing. But I'll keep experimenting.
